---
- hosts: 192.168.1.187
  user: vagrant
  sudo: True
  tasks:
     - name: install me
       action: apt name=mercurial state=installed


- hosts: 192.168.1.187
  user: vagrant
  tags: 
    - good
  tasks:

     - name: clone scm-hook
       action: hg repo=https://bitbucket.org/yeukhon/scm-hook dest=/home/vagrant/scm-hook
     - name: clone scm-hook idempotence
       action: hg repo=https://bitbucket.org/yeukhon/scm-hook dest=/home/vagrant/scm-hook
     - name: clone scm-hook idempotence with state=present explicit
       action: hg repo=https://bitbucket.org/yeukhon/scm-hook dest=/home/vagrant/scm-hook state=present
     - name: remove scm-hook
       action: file path=/home/vagrant/scm-hook state=absent

     - name: clone playground from ssh
       action: hg repo=ssh://hg@bitbucket.org/yeukhon/playground dest=/home/vagrant/playground
     - name: clone playground from ssh idempotence
       action: hg repo=ssh://hg@bitbucket.org/yeukhon/playground dest=/home/vagrant/playground
     - name: clone playground from ssh idempotence with revision and state=present
       action: hg repo=ssh://hg@bitbucket.org/yeukhon/playground dest=/home/vagrant/playground revision=default state=present

     - name: remove playground
       action: file path=/home/vagrant/playground state=absent

     - name: clone playground from three revisions 
       action: hg repo=ssh://hg@bitbucket.org/yeukhon/playground dest=/home/vagrant/playground revision=f21ccd8

     - name: clone playground from three revisions idempotence
       action: hg repo=ssh://hg@bitbucket.org/yeukhon/playground dest=/home/vagrant/playground revision=f21ccd8
     - name: clone update to one revision up
       action: hg repo=ssh://hg@bitbucket.org/yeukhon/playground dest=/home/vagrant/playground revision=72f75ae state=latest
     - name: clone update to one revision up idemptoence
       action: hg repo=ssh://hg@bitbucket.org/yeukhon/playground dest=/home/vagrant/playground revision=72f75ae state=latest
     - name: remove playground
       action: file path=/home/vagrant/playground state=absent

- hosts: 192.168.1.187
  user: vagrant
  tags:
     - force
  tasks:

     - name: clone scm-hook
       action: hg repo=https://bitbucket.org/yeukhon/scm-hook dest=/home/vagrant/scm-hook
     - name: make a file in scm-hook
       action: copy src=newfile.py dest=/home/vagrant/scm-hook/newfile.py
     - hg: repo=https://bitbucket.org/yeukhon/scm-hook dest=/home/vagrant/scm-hook force=yes
     - file: path=/home/vagrant/scm-hook/newfile.py state=absent
     - name: make a file in scm-hook again
       action: copy src=newfile.py dest=/home/vagrant/scm-hook/newfile.py
     - hg: repo=https://bitbucket.org/yeukhon/scm-hook dest=/home/vagrant/scm-hook force=no
     - file: path=/home/vagrant/scm-hook/newfile.py state=file
     - name: remove scm-hook
       action: file path=/home/vagrant/scm-hook state=absent

- hosts: 192.168.1.187
  user: vagrant

  tasks:

     - name: bad url
       tags:
        - bad_url
       action: hg repo=https://bitbucket.org/yeukhon/scm-hoo dest=/home/vagrant/scm-hook

     - name: bad revision
       tags:
        - bad_revision
       action: hg repo=https://bitbucket.org/yeukhon/scm-hook dest=/home/vagrant/scm-hook revision=random

